package com.planner.entity;

public enum ViolationType {
    TEACHER_WEEKLY_HOURS_TOO_LOW,
    TEACHER_DAILY_HOURS_TOO_HIGH,
    GROUP_TEACHER_COUNT_TOO_LOW,
    GROUP_TEACHER_COUNT_TOO_HIGH,
    BLOCK_OUTSIDE_GROUP_HOURS
}
