spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/planner
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:planner}
    password: ${DB_PASSWORD:planner}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
