spring:
  main:
    lazy-initialization: true
    banner-mode: off
  jmx:
    enabled: false
  liquibase:
    show-summary: never
  datasource:
    url: jdbc:sqlite:./planner.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none

management:
  health:
    defaults:
      enabled: false
    db:
      enabled: true

logging:
  level:
    root: WARN
    com.planner: INFO
    liquibase: WARN
    org.hibernate: WARN
    org.springframework: WARN
